apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml

namePrefix: jesses-

vars:
- name: SERVICE_NAME
  objref:
    kind: Service
    name: guestbook-svc
    apiVersion: v1
  fieldref:     # optional -- if omitted, defaults to metadata.name
    fieldpath: metadata.name
