apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- var-reference-in-selectors.yaml

resources:
- deployment.yaml
- service.yaml

vars:
- name: DEPLOYMENT_NAME
  objref:
    kind: Deployment
    name: guestbook
    apiVersion: apps/v1
