apiVersion: v1 
kind: FooPod   # use a kind unknown to kustomize
metadata:
  name: my-foo-pod
spec:
  random:
    path:
      which:
        has:
          containers:
          - name: guestbook
            image: guestbook:REPLACEME
          containerz: # containerz with a 'z'
          - name: guestbook
            image: guestbook:REPLACEME
