# The Kubernetes List kind is used, because YAML anchors and aliases can only reference
# objects in the same document
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: pod-a
  spec: &podSpec
    containers:
    - name: guestbook
      image: guestbook:v1
# the pods defined below are clones of the pod spec above (with different names)
- apiVersion: v1
  kind: Pod
  metadata:
    name: pod-b
  spec: *podSpec
- apiVersion: v1
  kind: Pod
  metadata:
    name: pod-c
  spec: *podSpec
