apiVersion: v1
kind: Pod
metadata:
  name: pod-a
spec:
  containers:
  - name: guestbook
    env:
    - name: FOO
      value: ham

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  containers:
  - name: guestbook
    env:
    - name: BAR
      value: spam

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
spec:
  containers:
  - name: guestbook
    env:
    - name: BAZ
      value: eggs
