apiVersion: v1
kind: Pod
metadata:
  name: pod-a
spec:
  serviceAccountName: sa-1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  serviceAccountName: sa-2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
spec:
  serviceAccountName: sa-3
