apiVersion: v1
kind: Pod
metadata:
  name: guestbook
spec:
  containers:
  - name: guestbook
    image: guestbook:latest
    volumeMounts:
    - name: logs
      mountPath: /usr/local/tomcat/logs/
  volumes:
  - name: logs
    emptyDir: {}
